"use client";

export type LocalDraft={id:string;workOrderId:string;serverVersion:number;answers:Record<string,unknown>;location:{latitude:number;longitude:number;accuracy?:number}|null;updatedAt:string;status:"DIRTY"|"SYNCED"|"CONFLICT";lastError?:string};
export type QueuedEvidence={id:string;workOrderId:string;draftId:string;fieldId:string;category:"BEFORE"|"DURING"|"AFTER"|"ISSUE"|"DOCUMENT"|"SIGNATURE"|"OTHER";blob:Blob;originalFilename:string;mimeType:string;sizeBytes:number;capturedAt:string;latitude?:number;longitude?:number;width?:number;height?:number;caption?:string;consentText?:string;checksumSha256?:string;status:"PENDING"|"UPLOADING"|"FAILED";attempts:number;lastError?:string};

const databaseName="fieldproof-offline";const databaseVersion=1;
function openDatabase():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(databaseName,databaseVersion);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("drafts"))db.createObjectStore("drafts",{keyPath:"workOrderId"});if(!db.objectStoreNames.contains("evidenceQueue")){const store=db.createObjectStore("evidenceQueue",{keyPath:"id"});store.createIndex("workOrderId","workOrderId");}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function requestResult<T>(storeName:"drafts"|"evidenceQueue",mode:IDBTransactionMode,run:(store:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const db=await openDatabase();return new Promise((resolve,reject)=>{const transaction=db.transaction(storeName,mode);const request=run(transaction.objectStore(storeName));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);transaction.oncomplete=()=>db.close();transaction.onerror=()=>reject(transaction.error);});}
export const getLocalDraft=(workOrderId:string)=>requestResult<LocalDraft|undefined>("drafts","readonly",(store)=>store.get(workOrderId));
export const putLocalDraft=(draft:LocalDraft)=>requestResult<IDBValidKey>("drafts","readwrite",(store)=>store.put(draft));
export const deleteLocalDraft=(workOrderId:string)=>requestResult<undefined>("drafts","readwrite",(store)=>store.delete(workOrderId));
export const putQueuedEvidence=(evidence:QueuedEvidence)=>requestResult<IDBValidKey>("evidenceQueue","readwrite",(store)=>store.put(evidence));
export const deleteQueuedEvidence=(id:string)=>requestResult<undefined>("evidenceQueue","readwrite",(store)=>store.delete(id));
export async function listQueuedEvidence(workOrderId:string):Promise<QueuedEvidence[]>{const db=await openDatabase();return new Promise((resolve,reject)=>{const transaction=db.transaction("evidenceQueue","readonly");const request=transaction.objectStore("evidenceQueue").index("workOrderId").getAll(workOrderId);request.onsuccess=()=>resolve(request.result as QueuedEvidence[]);request.onerror=()=>reject(request.error);transaction.oncomplete=()=>db.close();});}
export async function countUnsynced():Promise<number>{const db=await openDatabase();return new Promise((resolve,reject)=>{const transaction=db.transaction(["drafts","evidenceQueue"],"readonly");let drafts=0;let evidence=0;const draftRequest=transaction.objectStore("drafts").getAll();const evidenceRequest=transaction.objectStore("evidenceQueue").count();draftRequest.onsuccess=()=>{drafts=(draftRequest.result as LocalDraft[]).filter((item)=>item.status!=="SYNCED").length;};evidenceRequest.onsuccess=()=>{evidence=evidenceRequest.result;};transaction.oncomplete=()=>{db.close();resolve(drafts+evidence);};transaction.onerror=()=>reject(transaction.error);});}
export function signalOfflineStateChanged(){window.dispatchEvent(new CustomEvent("fieldproof:offline-state-changed"));}
