import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Copy, ExternalLink, Printer } from "lucide-react";
import { PageHeader } from "@/components/forms/master-data";
import { StatusBadge } from "@/components/work-orders/status-badge";
import { WorkOrderForm } from "@/components/work-orders/work-order-form";
import { hasPermission } from "@/modules/memberships/permissions";
import { getWorkOrder, getWorkOrderFormOptions } from "@/modules/work-orders/service";
import { requireTenantContext } from "@/server/auth/tenant";
import { cancelWorkOrderAction, duplicateWorkOrderAction, updateWorkOrderAction } from "../../work-order-actions";

export default async function WorkOrderDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){const[tenant,route,query]=await Promise.all([requireTenantContext(),params,searchParams]);if(!hasPermission(tenant.role,"work_order:manage"))redirect("/app/dashboard");const[detail,options]=await Promise.all([getWorkOrder(tenant.organizationId,route.id),getWorkOrderFormOptions(tenant.organizationId)]);if(!detail)notFound();const work=detail.workOrder;const editable=["DRAFT","SCHEDULED","ASSIGNED"].includes(work.status);return <main><PageHeader eyebrow={work.number} title={work.title} description={`${detail.clientName} · ${detail.siteName}`}/>{query.saved?<p className="mt-4 rounded-xl bg-green-50 p-3 text-sm font-bold text-green-800">Perubahan tersimpan.</p>:null}
  <div className="mt-5 flex flex-wrap items-center gap-2"><StatusBadge status={work.status}/><span className="rounded-full bg-coral-50 px-3 py-1 text-xs font-extrabold text-coral-700">{work.priority}</span><Link href={`/app/work-orders/${work.id}/print`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><Printer className="size-4"/>Printable</Link><form action={duplicateWorkOrderAction}><input type="hidden" name="id" value={work.id}/><button className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><Copy className="size-4"/>Duplicate</button></form></div>
  <section className="mt-5 grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-3"><div><p className="text-xs font-extrabold uppercase text-muted">Schedule</p><p className="mt-1 font-bold">{work.scheduleStart?.toLocaleString("id-ID")??"Belum dijadwalkan"}</p><p className="text-sm text-ink-soft">hingga {work.scheduleEnd?.toLocaleString("id-ID")??"—"}</p></div><div><p className="text-xs font-extrabold uppercase text-muted">Template</p><p className="mt-1 font-bold">{detail.templateName} · v{detail.templateVersion}</p><p className="text-sm text-ink-soft">Immutable snapshot</p></div><div><p className="text-xs font-extrabold uppercase text-muted">Assignee</p><p className="mt-1 font-bold">{detail.assignees.map((item)=>item.name).join(", ")||"Belum ditugaskan"}</p><p className="text-sm text-ink-soft">Team: {detail.teamName??"—"}</p></div><div className="md:col-span-3"><p className="text-xs font-extrabold uppercase text-muted">Instructions</p><p className="mt-1 whitespace-pre-wrap text-sm">{work.instructions||"Tidak ada instruksi khusus."}</p></div><Link href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(detail.siteAddress)}`} target="_blank" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-coral-700 md:col-span-3">Buka lokasi di peta<ExternalLink className="size-4"/></Link></section>
  {editable?<details className="mt-5 rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-extrabold text-coral-700">Edit planning & assignment</summary><div className="mt-5"><WorkOrderForm action={updateWorkOrderAction} options={options} existing={work} assigneeIds={detail.assignees.map((item)=>item.membershipId)}/></div></details>:null}
  {work.status!=="CANCELLED"&&work.status!=="COMPLETED"?<details className="mt-5 rounded-2xl border border-red-200 bg-white p-5"><summary className="cursor-pointer font-extrabold text-danger">Cancel work order</summary><form action={cancelWorkOrderAction} className="mt-4 flex flex-col gap-3 sm:flex-row"><input type="hidden" name="id" value={work.id}/><input required minLength={3} name="reason" placeholder="Alasan pembatalan" className="min-h-11 flex-1 rounded-xl border px-4"/><button className="min-h-11 rounded-xl bg-danger px-5 font-bold text-white">Batalkan</button></form></details>:null}
  <section className="mt-7"><h2 className="text-xl font-extrabold">Activity timeline</h2><div className="mt-4 border-l-2 border-coral-200 pl-5">{detail.history.map(({history,actorName})=><article key={history.id} className="relative mb-5 rounded-xl border bg-white p-4 before:absolute before:-left-[1.72rem] before:top-5 before:size-3 before:rounded-full before:bg-coral-500"><p className="font-extrabold">{history.fromStatus?`${history.fromStatus} → `:""}{history.toStatus}</p><p className="mt-1 text-sm text-ink-soft">{history.reason||"Status transition"} · {actorName||"System"}</p><time className="mt-2 block text-xs text-muted">{history.createdAt.toLocaleString("id-ID")}</time></article>)}</div></section></main>}
