import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/forms/master-data";
import { hasPermission } from "@/modules/memberships/permissions";
import { listWorkOrders } from "@/modules/work-orders/service";
import { workOrderStatuses } from "@/modules/work-orders/state-machine";
import { requireTenantContext } from "@/server/auth/tenant";

export default async function WorkOrderKanban(){const tenant=await requireTenantContext();if(!hasPermission(tenant.role,"work_order:manage"))redirect("/app/dashboard");const data=await listWorkOrders({organizationId:tenant.organizationId,sort:"newest",page:1,pageSize:500});return <main className="min-w-0"><PageHeader eyebrow="Work orders" title="Kanban status" description="Snapshot pekerjaan menurut tahap workflow. Perubahan status tetap dilakukan melalui domain action yang valid."/><div className="mt-6 flex gap-4 overflow-x-auto pb-5">{workOrderStatuses.map((status)=>{const rows=data.rows.filter((row)=>row.workOrder.status===status);return <section key={status} className="w-72 shrink-0 rounded-2xl bg-cream-100 p-3"><div className="flex items-center justify-between px-1"><h2 className="text-sm font-extrabold">{status.replaceAll("_"," ")}</h2><span className="rounded-full bg-white px-2 py-1 text-xs font-bold">{rows.length}</span></div><div className="mt-3 space-y-2">{rows.map(({workOrder,clientName,siteName})=><Link href={`/app/work-orders/${workOrder.id}`} key={workOrder.id} className="block rounded-xl border bg-white p-4 shadow-sm hover:border-coral-300"><p className="text-xs font-extrabold text-coral-700">{workOrder.number}</p><p className="mt-1 font-bold">{workOrder.title}</p><p className="mt-2 text-xs text-muted">{clientName} · {siteName}</p><p className="mt-2 text-xs font-bold">{workOrder.priority}</p></Link>)}{!rows.length?<p className="rounded-xl border border-dashed p-4 text-center text-xs text-muted">Kosong</p>:null}</div></section>})}</div></main>}
