import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { eq } from "drizzle-orm";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { emptyChecklistSchema } from "@/modules/templates/validation";
import { checklistTemplates,checklistTemplateVersions,clients,memberships,organizations,sites,submissionRevisions,submissions,users,workOrderAssignments,workOrderDrafts,workOrders } from "@/server/db/schema";

describe("execution persistence boundaries",()=>{const client=new PGlite();const db=drizzle(client);let organizationId:string;let membershipId:string;let workOrderId:string;let submissionId:string;
  beforeAll(async()=>{await migrate(db,{migrationsFolder:"drizzle"});const[user]=await db.insert(users).values({name:"Worker",email:"snapshot-worker@test.local"}).returning({id:users.id});const[org]=await db.insert(organizations).values({name:"Execution Org",slug:"execution-snapshot-org"}).returning({id:organizations.id});organizationId=org.id;const[member]=await db.insert(memberships).values({organizationId,userId:user.id,role:"FIELD_WORKER"}).returning({id:memberships.id});membershipId=member.id;const[customer]=await db.insert(clients).values({organizationId,createdById:user.id,code:"EX",name:"Client"}).returning({id:clients.id});const[site]=await db.insert(sites).values({organizationId,clientId:customer.id,createdById:user.id,code:"EX-S",name:"Site",address:"Address"}).returning({id:sites.id});const[template]=await db.insert(checklistTemplates).values({organizationId,createdById:user.id,name:"Execution",draftSchema:emptyChecklistSchema(),status:"PUBLISHED",currentVersion:1}).returning({id:checklistTemplates.id});const[version]=await db.insert(checklistTemplateVersions).values({organizationId,templateId:template.id,version:1,schemaSnapshot:emptyChecklistSchema(),createdById:user.id}).returning({id:checklistTemplateVersions.id});const[work]=await db.insert(workOrders).values({organizationId,createdById:user.id,number:"WO-EXEC-1",title:"Execution",clientId:customer.id,siteId:site.id,templateVersionId:version.id,status:"IN_PROGRESS"}).returning({id:workOrders.id});workOrderId=work.id;await db.insert(workOrderAssignments).values({workOrderId,membershipId,assignedById:user.id});const[submission]=await db.insert(submissions).values({organizationId,workOrderId,currentRevision:1}).returning({id:submissions.id});submissionId=submission.id;await db.insert(submissionRevisions).values({organizationId,submissionId,workOrderId,revision:1,templateSnapshot:emptyChecklistSchema(),answersSnapshot:{answer:"original"},evidenceSnapshot:[],submittedByMembershipId:membershipId,appVersion:"test",finishedAt:new Date()});});afterAll(async()=>client.close());
  it("keeps an existing submission revision immutable when drafts change",async()=>{await db.insert(workOrderDrafts).values({id:crypto.randomUUID(),organizationId,workOrderId,membershipId,answers:{answer:"changed"},clientUpdatedAt:new Date()});const[revision]=await db.select().from(submissionRevisions).where(eq(submissionRevisions.submissionId,submissionId));expect(revision.answersSnapshot).toEqual({answer:"original"});});
  it("enforces monotonically unique revision numbers",async()=>{await expect(db.insert(submissionRevisions).values({organizationId,submissionId,workOrderId,revision:1,templateSnapshot:{},answersSnapshot:{},evidenceSnapshot:[],submittedByMembershipId:membershipId,appVersion:"test",finishedAt:new Date()})).rejects.toThrow();});
  it("allows only one server draft per work-order member",async()=>{await expect(db.insert(workOrderDrafts).values({id:crypto.randomUUID(),organizationId,workOrderId,membershipId,answers:{},clientUpdatedAt:new Date()})).rejects.toThrow();});
});
