import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { workOrderTenantPredicate } from "@/modules/work-orders/service";
import { emptyChecklistSchema } from "@/modules/templates/validation";
import { checklistTemplates, checklistTemplateVersions, clients, organizations, sites, users, workOrders } from "@/server/db/schema";

describe("work order tenant isolation and recurrence idempotency",()=>{const client=new PGlite();const db=drizzle(client);let orgA:string;let orgB:string;let workOrderId:string;let actorId:string;let clientId:string;let siteId:string;let templateVersionId:string;
  beforeAll(async()=>{await migrate(db,{migrationsFolder:"drizzle"});const[actor]=await db.insert(users).values({name:"Admin",email:"wo-admin@test.local"}).returning({id:users.id});actorId=actor.id;const orgs=await db.insert(organizations).values([{name:"Org A",slug:"wo-org-a"},{name:"Org B",slug:"wo-org-b"}]).returning({id:organizations.id});orgA=orgs[0].id;orgB=orgs[1].id;const[c]=await db.insert(clients).values({organizationId:orgB,createdById:actorId,code:"B",name:"Client B"}).returning({id:clients.id});clientId=c.id;const[s]=await db.insert(sites).values({organizationId:orgB,clientId,createdById:actorId,code:"B-S",name:"Site B",address:"B"}).returning({id:sites.id});siteId=s.id;const[t]=await db.insert(checklistTemplates).values({organizationId:orgB,createdById:actorId,name:"Template",draftSchema:emptyChecklistSchema(),status:"PUBLISHED",currentVersion:1}).returning({id:checklistTemplates.id});const[v]=await db.insert(checklistTemplateVersions).values({organizationId:orgB,templateId:t.id,version:1,schemaSnapshot:emptyChecklistSchema(),createdById:actorId}).returning({id:checklistTemplateVersions.id});templateVersionId=v.id;const[wo]=await db.insert(workOrders).values({organizationId:orgB,createdById:actorId,number:"WO-B-1",title:"Foreign",clientId,siteId,templateVersionId}).returning({id:workOrders.id});workOrderId=wo.id;});afterAll(async()=>client.close());
  it("does not expose another tenant's work order by UUID",async()=>expect(await db.select().from(workOrders).where(workOrderTenantPredicate(orgA,workOrderId))).toHaveLength(0));
  it("prevents duplicate recurrence occurrences at database level",async()=>{const series=crypto.randomUUID();const occurrence=new Date("2026-08-01T02:00:00Z");const values={organizationId:orgB,createdById:actorId,title:"Recurring",clientId,siteId,templateVersionId,recurrenceSeriesId:series,recurrenceOccurrenceAt:occurrence};await db.insert(workOrders).values({...values,number:"WO-R-1"});await expect(db.insert(workOrders).values({...values,number:"WO-R-2"})).rejects.toThrow();});
});
