import { inputClass, Submit, TextAreaField } from "@/components/forms/master-data";

type Options = { clients:Array<{id:string;name:string}>;sites:Array<{id:string;clientId:string;name:string}>;templates:Array<{id:string;version:number;templateName:string}>;teams:Array<{id:string;name:string}>;members:Array<{id:string;name:string;role:string}> };
type Existing = { id:string; rowVersion:number; title:string;description:string|null;clientId:string;siteId:string;templateVersionId:string;priority:string;scheduleStart:Date|null;scheduleEnd:Date|null;dueDate:Date|null;teamId:string|null;supervisorMembershipId:string|null;internalNotes:string|null;instructions:string|null;tags:string[];clientVisibility:boolean;clientApprovalRequired:boolean;recurrenceFrequency:string|null;recurrenceInterval:number|null;recurrenceEndAt:Date|null };

const localDateTime=(value:Date|null|undefined)=>value?new Date(value.getTime()-value.getTimezoneOffset()*60_000).toISOString().slice(0,16):"";

export function WorkOrderForm({action,options,existing,assigneeIds=[]}:{action:(formData:FormData)=>void|Promise<void>;options:Options;existing?:Existing;assigneeIds?:string[]}){
  const supervisors=options.members.filter((member)=>["OWNER","ADMIN","SUPERVISOR"].includes(member.role));
  const assignees=options.members.filter((member)=>["FIELD_WORKER","SUPERVISOR"].includes(member.role));
  return <form action={action} className="grid gap-4 sm:grid-cols-2">{existing?<><input type="hidden" name="id" value={existing.id}/><input type="hidden" name="rowVersion" value={existing.rowVersion}/></>:null}
    <label className="text-sm font-bold sm:col-span-2">Judul pekerjaan<input required name="title" defaultValue={existing?.title??""} className={inputClass}/></label>
    <label className="text-sm font-bold">Client<select required name="clientId" defaultValue={existing?.clientId??""} className={inputClass}><option value="">Pilih client</option>{options.clients.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="text-sm font-bold">Site<select required name="siteId" defaultValue={existing?.siteId??""} className={inputClass}><option value="">Pilih site</option>{options.sites.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="text-sm font-bold">Template version<select required name="templateVersionId" defaultValue={existing?.templateVersionId??""} className={inputClass}><option value="">Pilih versi published</option>{options.templates.map((item)=><option key={item.id} value={item.id}>{item.templateName} · v{item.version}</option>)}</select></label>
    <label className="text-sm font-bold">Priority<select name="priority" defaultValue={existing?.priority??"NORMAL"} className={inputClass}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label>
    <label className="text-sm font-bold">Schedule start<input type="datetime-local" name="scheduleStart" defaultValue={localDateTime(existing?.scheduleStart)} className={inputClass}/></label><label className="text-sm font-bold">Schedule end<input type="datetime-local" name="scheduleEnd" defaultValue={localDateTime(existing?.scheduleEnd)} className={inputClass}/></label><label className="text-sm font-bold">Due date<input type="datetime-local" name="dueDate" defaultValue={localDateTime(existing?.dueDate)} className={inputClass}/></label>
    <label className="text-sm font-bold">Team<select name="teamId" defaultValue={existing?.teamId??""} className={inputClass}><option value="">Tanpa team</option>{options.teams.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="text-sm font-bold">Supervisor<select name="supervisorMembershipId" defaultValue={existing?.supervisorMembershipId??""} className={inputClass}><option value="">Belum ditentukan</option>{supervisors.map((item)=><option key={item.id} value={item.id}>{item.name} · {item.role}</option>)}</select></label>
    <label className="text-sm font-bold">Tags<input name="tags" defaultValue={existing?.tags.join(", ")??""} placeholder="cleaning, urgent" className={inputClass}/></label>
    <div className="sm:col-span-2"><TextAreaField label="Description" name="description" defaultValue={existing?.description}/></div><div className="sm:col-span-2"><TextAreaField label="Instructions untuk petugas" name="instructions" defaultValue={existing?.instructions}/></div><div className="sm:col-span-2"><TextAreaField label="Internal notes" name="internalNotes" defaultValue={existing?.internalNotes}/></div>
    <fieldset className="rounded-xl border p-4 sm:col-span-2"><legend className="px-2 text-sm font-extrabold">Assignee</legend><div className="grid gap-2 sm:grid-cols-2">{assignees.map((member)=><label key={member.id} className="flex min-h-11 items-center gap-3 rounded-lg bg-cream-50 px-3 text-sm font-bold"><input type="checkbox" name="assigneeIds" value={member.id} defaultChecked={assigneeIds.includes(member.id)}/>{member.name}<span className="text-xs text-muted">{member.role}</span></label>)}{!assignees.length?<p className="text-sm text-muted">Belum ada field worker aktif.</p>:null}</div></fieldset>
    <fieldset className="rounded-xl border p-4 sm:col-span-2"><legend className="px-2 text-sm font-extrabold">Recurrence</legend><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-bold">Frequency<select name="recurrenceFrequency" defaultValue={existing?.recurrenceFrequency??""} className={inputClass}><option value="">Tidak berulang</option><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option></select></label><label className="text-sm font-bold">Setiap<input type="number" min="1" max="365" name="recurrenceInterval" defaultValue={existing?.recurrenceInterval??1} className={inputClass}/></label><label className="text-sm font-bold">Berakhir<input type="datetime-local" name="recurrenceEndAt" defaultValue={localDateTime(existing?.recurrenceEndAt)} className={inputClass}/></label></div></fieldset>
    <label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" name="clientVisibility" defaultChecked={existing?.clientVisibility}/> Terlihat oleh client</label><label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" name="clientApprovalRequired" defaultChecked={existing?.clientApprovalRequired}/> Memerlukan approval client</label>
    <div className="sm:col-span-2"><Submit>{existing?"Simpan work order":"Buat work order"}</Submit></div>
  </form>;
}
