import Link from "next/link";
import { redirect } from "next/navigation";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { PageHeader } from "@/components/forms/master-data";
import { hasPermission } from "@/modules/memberships/permissions";
import { listScheduledWorkOrders } from "@/modules/work-orders/service";
import { requireTenantContext } from "@/server/auth/tenant";

const key=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
export default async function WorkOrderCalendar({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const[tenant,query]=await Promise.all([requireTenantContext(),searchParams]);if(!hasPermission(tenant.role,"work_order:manage"))redirect("/app/dashboard");const match=/^(\d{4})-(\d{2})$/.exec(query.month??"");const now=new Date();const year=match?Number(match[1]):now.getFullYear();const month=match?Number(match[2])-1:now.getMonth();const from=new Date(year,month,1);const to=new Date(year,month+1,1);const rows=await listScheduledWorkOrders(tenant.organizationId,from,to);const byDay=new Map<string,typeof rows>();for(const row of rows){const dateKey=key(row.workOrder.scheduleStart!);byDay.set(dateKey,[...(byDay.get(dateKey)??[]),row]);}const start=new Date(year,month,1-from.getDay());const days=Array.from({length:42},(_,index)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+index));const previous=new Date(year,month-1,1);const next=new Date(year,month+1,1);return <main><PageHeader eyebrow="Work orders" title="Calendar" description="Jadwal pekerjaan per bulan berdasarkan schedule start."/><div className="mt-5 flex items-center justify-between"><Link href={`/app/work-orders/calendar?month=${key(previous).slice(0,7)}`} className="grid min-h-11 min-w-11 place-items-center rounded-xl border bg-white"><ChevronLeft/></Link><h2 className="text-xl font-extrabold">{from.toLocaleDateString("id-ID",{month:"long",year:"numeric"})}</h2><Link href={`/app/work-orders/calendar?month=${key(next).slice(0,7)}`} className="grid min-h-11 min-w-11 place-items-center rounded-xl border bg-white"><ChevronRight/></Link></div><div className="mt-4 grid grid-cols-7 overflow-hidden rounded-2xl border bg-white">{["Min","Sen","Sel","Rab","Kam","Jum","Sab"].map((day)=><div key={day} className="border-b bg-cream-100 p-2 text-center text-xs font-extrabold">{day}</div>)}{days.map((day)=><div key={day.toISOString()} className={`min-h-28 border-b border-r p-2 ${day.getMonth()!==month?"bg-slate-50 text-muted":""}`}><p className="text-xs font-extrabold">{day.getDate()}</p><div className="mt-1 space-y-1">{(byDay.get(key(day))??[]).slice(0,3).map(({workOrder})=><Link key={workOrder.id} href={`/app/work-orders/${workOrder.id}`} className="block truncate rounded-md bg-coral-50 px-2 py-1 text-[11px] font-bold text-coral-800">{workOrder.scheduleStart?.toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})} {workOrder.title}</Link>)}</div></div>)}</div></main>}
