"use client";
/* eslint-disable react-hooks/refs -- dnd-kit intentionally exposes mutable ref-backed sortable state. */

import { DndContext, PointerSensor, closestCenter, useDraggable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, verticalListSortingStrategy, useSortable } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { CopyPlus, GripVertical, Plus, Trash2 } from "lucide-react";
import { useState } from "react";

import { checklistFieldTypes, type ChecklistField, type ChecklistFieldType, type ChecklistSchema } from "@/modules/templates/validation";
import { inputClass } from "@/components/forms/master-data";

const labels: Record<ChecklistFieldType, string> = {
  SECTION_HEADING: "Section heading", INSTRUCTION: "Instruction", SHORT_TEXT: "Short text", LONG_TEXT: "Long text", NUMBER: "Number", DATE: "Date", TIME: "Time", DATETIME: "Date & time", SINGLE_SELECT: "Single select", MULTI_SELECT: "Multi select", CHECKBOX: "Checkbox", PASS_FAIL_NA: "Pass / Fail / N/A", RATING: "Rating", PHOTO: "Photo", SIGNATURE: "Signature", GPS: "GPS", BARCODE_QR: "Barcode / QR",
};

type BuilderProps = { template: { id: string; name: string; description: string | null; industry: string | null; category: string | null; estimatedMinutes: number | null; rowVersion: number; draftSchema: ChecklistSchema }; action: (formData: FormData) => void | Promise<void> };

function newField(type: ChecklistFieldType): ChecklistField {
  return { id: crypto.randomUUID(), type, label: labels[type], required: !["SECTION_HEADING", "INSTRUCTION"].includes(type), options: ["SINGLE_SELECT", "MULTI_SELECT"].includes(type) ? ["Option 1", "Option 2"] : [], visibleInReport: true, ...(type === "RATING" ? { min: 1, max: 5 } : {}), ...(type === "PHOTO" ? { allowedFileCount: 3 } : {}) };
}

function PaletteButton({ type, add }: { type: ChecklistFieldType; add: () => void }) {
  const draggable = useDraggable({ id: `palette:${type}`, data: { kind: "palette", fieldType: type } });
  return <button ref={draggable.setNodeRef} type="button" onClick={add} className="min-h-11 cursor-grab rounded-xl border px-3 text-left text-xs font-bold hover:border-coral-300 hover:bg-coral-50" {...draggable.attributes} {...draggable.listeners}><Plus className="mr-1 inline size-4"/>{labels[type]}</button>;
}

function SortableField({ field, sectionId, update, remove, duplicate }: { field: ChecklistField; sectionId: string; update: (patch: Partial<ChecklistField>) => void; remove: () => void; duplicate: () => void }) {
  const sortable = useSortable({ id: `field:${field.id}`, data: { kind: "field", sectionId, fieldId: field.id } });
  return <article ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} className="rounded-xl border border-border bg-white p-4 shadow-sm">
    <div className="flex items-start gap-3"><button type="button" aria-label="Geser field" className="grid min-h-11 min-w-11 cursor-grab place-items-center rounded-lg text-muted hover:bg-cream-100" {...sortable.attributes} {...sortable.listeners}><GripVertical className="size-5" /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-coral-50 px-2 py-1 text-xs font-extrabold text-coral-700">{labels[field.type]}</span><input aria-label="Label field" value={field.label} onChange={(event) => update({ label: event.target.value })} className="min-h-11 min-w-48 flex-1 rounded-lg border px-3 font-bold" /></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><input aria-label="Deskripsi field" value={field.description ?? ""} onChange={(event) => update({ description: event.target.value || undefined })} placeholder="Deskripsi / petunjuk" className="min-h-11 rounded-lg border px-3 text-sm" />
      <label className="flex min-h-11 items-center gap-2 text-sm font-bold"><input type="checkbox" checked={field.required} onChange={(event) => update({ required: event.target.checked })} /> Wajib diisi</label></div>
      {["SINGLE_SELECT", "MULTI_SELECT"].includes(field.type) ? <label className="mt-3 block text-xs font-bold">Opsi (satu per baris)<textarea value={field.options.join("\n")} onChange={(event) => update({ options: event.target.value.split("\n").filter(Boolean) })} className="mt-1 min-h-20 w-full rounded-lg border p-3 text-sm" /></label> : null}
      {["NUMBER", "RATING"].includes(field.type) ? <div className="mt-3 grid grid-cols-2 gap-3"><input type="number" value={field.min ?? ""} onChange={(event) => update({ min: event.target.value === "" ? undefined : Number(event.target.value) })} placeholder="Minimum" className="min-h-11 rounded-lg border px-3"/><input type="number" value={field.max ?? ""} onChange={(event) => update({ max: event.target.value === "" ? undefined : Number(event.target.value) })} placeholder="Maximum" className="min-h-11 rounded-lg border px-3"/></div> : null}
      {field.type === "PHOTO" ? <div className="mt-3 grid grid-cols-2 gap-3"><input type="number" min="1" max="20" value={field.allowedFileCount ?? 1} onChange={(event)=>update({ allowedFileCount:Number(event.target.value) })} aria-label="Jumlah file diizinkan" className="min-h-11 rounded-lg border px-3"/><input value={field.photoCategory ?? ""} onChange={(event)=>update({ photoCategory:event.target.value||undefined })} placeholder="Photo category" className="min-h-11 rounded-lg border px-3"/></div>:null}
      <details className="mt-3 rounded-xl bg-cream-50 p-3"><summary className="cursor-pointer text-xs font-extrabold text-coral-700">Konfigurasi lanjutan</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={field.placeholder ?? ""} onChange={(event)=>update({placeholder:event.target.value||undefined})} placeholder="Placeholder" className="min-h-11 rounded-lg border px-3 text-sm"/><input value={field.validationMessage ?? ""} onChange={(event)=>update({validationMessage:event.target.value||undefined})} placeholder="Validation message" className="min-h-11 rounded-lg border px-3 text-sm"/><textarea value={field.workerInstruction ?? ""} onChange={(event)=>update({workerInstruction:event.target.value||undefined})} placeholder="Worker instruction" className="min-h-20 rounded-lg border p-3 text-sm sm:col-span-2"/><label className="flex min-h-11 items-center gap-2 text-sm font-bold"><input type="checkbox" checked={field.visibleInReport} onChange={(event)=>update({visibleInReport:event.target.checked})}/> Tampilkan di final report</label></div></details>
    </div><div className="flex"><button type="button" aria-label="Duplikasi field" onClick={duplicate} className="grid min-h-11 min-w-11 place-items-center rounded-lg hover:bg-cream-100"><CopyPlus className="size-4" /></button><button type="button" aria-label="Hapus field" onClick={remove} className="grid min-h-11 min-w-11 place-items-center rounded-lg text-danger hover:bg-red-50"><Trash2 className="size-4" /></button></div></div>
  </article>;
}

export function TemplateBuilder({ template, action }: BuilderProps) {
  const [schema, setSchema] = useState(template.draftSchema);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));
  const updateSection = (sectionId: string, mutate: (section: ChecklistSchema["sections"][number]) => ChecklistSchema["sections"][number]) => setSchema((value) => ({ ...value, sections: value.sections.map((section) => section.id === sectionId ? mutate(section) : section) }));
  const addField = (sectionId: string, type: ChecklistFieldType) => updateSection(sectionId, (section) => ({ ...section, fields: [...section.fields, newField(type)] }));
  const onDragEnd = ({ active, over }: DragEndEvent) => {
    if (!over || active.id === over.id) return;
    const activeData = active.data.current; const overData = over.data.current;
    if (activeData?.kind === "palette") {
      const sectionId = overData?.sectionId;
      if (sectionId) addField(sectionId, activeData.fieldType as ChecklistFieldType);
      return;
    }
    if (activeData?.kind === "section" && overData?.kind === "section") {
      setSchema((value) => ({ ...value, sections: arrayMove(value.sections, value.sections.findIndex((item) => item.id === activeData.sectionId), value.sections.findIndex((item) => item.id === overData.sectionId)) })); return;
    }
    if (activeData?.kind !== "field") return;
    const targetSectionId = overData?.kind === "field" ? overData.sectionId : overData?.sectionId;
    if (!targetSectionId) return;
    setSchema((value) => {
      const sourceIndex = value.sections.findIndex((section) => section.id === activeData.sectionId); const targetIndex = value.sections.findIndex((section) => section.id === targetSectionId);
      if (sourceIndex < 0 || targetIndex < 0) return value;
      const sections = value.sections.map((section) => ({ ...section, fields: [...section.fields] }));
      const fieldIndex = sections[sourceIndex].fields.findIndex((item) => item.id === activeData.fieldId); const [moved] = sections[sourceIndex].fields.splice(fieldIndex, 1);
      const overFieldIndex = overData?.kind === "field" ? sections[targetIndex].fields.findIndex((item) => item.id === overData.fieldId) : sections[targetIndex].fields.length;
      sections[targetIndex].fields.splice(Math.max(0, overFieldIndex), 0, moved); return { ...value, sections };
    });
  };
  return <form action={action} className="mt-6 grid gap-6 xl:grid-cols-[260px_minmax(0,1fr)]"><input type="hidden" name="id" value={template.id}/><input type="hidden" name="rowVersion" value={template.rowVersion}/><input type="hidden" name="schema" value={JSON.stringify(schema)}/><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}>
    <aside className="self-start rounded-2xl border bg-white p-4 xl:sticky xl:top-5"><h2 className="font-extrabold">Field palette</h2><p className="mt-1 text-xs text-ink-soft">Klik untuk section pertama, atau tarik langsung ke section tujuan.</p><div className="mt-3 grid grid-cols-2 gap-2 xl:grid-cols-1">{checklistFieldTypes.map((type)=><PaletteButton key={type} type={type} add={()=>addField(schema.sections[0].id,type)}/>)}</div></aside>
    <div><section className="grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><label className="text-sm font-bold">Nama template<input required name="name" defaultValue={template.name} className={inputClass}/></label><label className="text-sm font-bold">Kategori<input name="category" defaultValue={template.category ?? ""} className={inputClass}/></label><label className="text-sm font-bold">Industri<input name="industry" defaultValue={template.industry ?? ""} className={inputClass}/></label><label className="text-sm font-bold">Estimasi (menit)<input type="number" min="1" name="estimatedMinutes" defaultValue={template.estimatedMinutes ?? ""} className={inputClass}/></label><label className="text-sm font-bold sm:col-span-2">Deskripsi<textarea name="description" defaultValue={template.description ?? ""} className={`${inputClass} min-h-24 py-3`}/></label></section>
      <SortableContext items={schema.sections.map((section)=>`section:${section.id}`)} strategy={verticalListSortingStrategy}><div className="mt-5 space-y-5">{schema.sections.map((section, sectionIndex)=>{
        const sortable = { id: `section:${section.id}` }; return <SortableSection key={section.id} sortable={sortable} section={section} sectionIndex={sectionIndex} canDelete={schema.sections.length > 1} onTitle={(title)=>updateSection(section.id,(value)=>({...value,title}))} onDelete={()=>setSchema((value)=>{const removedFieldIds=new Set(section.fields.map((field)=>field.id));return {...value,sections:value.sections.filter((item)=>item.id!==section.id),evidenceRules:value.evidenceRules.filter((rule)=>!rule.fieldId||!removedFieldIds.has(rule.fieldId))};})} onAdd={(type)=>addField(section.id,type)}>{section.fields.map((field)=><SortableField key={field.id} field={field} sectionId={section.id} update={(patch)=>updateSection(section.id,(value)=>({...value,fields:value.fields.map((item)=>item.id===field.id?{...item,...patch}:item)}))} remove={()=>setSchema((value)=>({...value,sections:value.sections.map((item)=>item.id===section.id?{...item,fields:item.fields.filter((candidate)=>candidate.id!==field.id)}:item),evidenceRules:value.evidenceRules.filter((rule)=>rule.fieldId!==field.id)}))} duplicate={()=>updateSection(section.id,(value)=>({...value,fields:[...value.fields,{...field,id:crypto.randomUUID(),label:`${field.label} (Copy)`}]}))}/>)}</SortableSection>;
      })}</div></SortableContext>
      <button type="button" onClick={()=>setSchema((value)=>({...value,sections:[...value.sections,{id:crypto.randomUUID(),title:`Bagian ${value.sections.length+1}`,fields:[]}]}))} className="mt-5 min-h-11 rounded-xl border border-dashed border-coral-400 px-5 font-bold text-coral-700">+ Tambah section</button>
      <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-extrabold">Required evidence rules</h2><p className="mt-1 text-sm text-ink-soft">Aturan ini divalidasi saat petugas menyelesaikan pekerjaan.</p><div className="mt-4 space-y-3">{schema.evidenceRules.map((rule,index)=><div key={rule.id} className="grid gap-2 rounded-xl bg-cream-50 p-3 sm:grid-cols-[1fr_1fr_100px_44px]"><select value={rule.type} onChange={(event)=>setSchema((value)=>({...value,evidenceRules:value.evidenceRules.map((item)=>item.id===rule.id?{...item,type:event.target.value as typeof rule.type}:item)}))} className="min-h-11 rounded-lg border bg-white px-3 text-sm font-bold"><option value="MIN_PHOTOS">Minimum photos</option><option value="REQUIRE_GPS">Require GPS</option><option value="REQUIRE_SIGNATURE">Require signature</option></select><select value={rule.fieldId??""} onChange={(event)=>setSchema((value)=>({...value,evidenceRules:value.evidenceRules.map((item)=>item.id===rule.id?{...item,fieldId:event.target.value||undefined}:item)}))} className="min-h-11 rounded-lg border bg-white px-3 text-sm"><option value="">Seluruh template</option>{schema.sections.flatMap((section)=>section.fields).map((field)=><option key={field.id} value={field.id}>{field.label}</option>)}</select><input aria-label="Minimum evidence" type="number" min="1" max="20" disabled={rule.type!=="MIN_PHOTOS"} value={rule.minCount??1} onChange={(event)=>setSchema((value)=>({...value,evidenceRules:value.evidenceRules.map((item)=>item.id===rule.id?{...item,minCount:Number(event.target.value)}:item)}))} className="min-h-11 rounded-lg border bg-white px-3"/><button type="button" aria-label={`Hapus evidence rule ${index+1}`} onClick={()=>setSchema((value)=>({...value,evidenceRules:value.evidenceRules.filter((item)=>item.id!==rule.id)}))} className="grid min-h-11 place-items-center rounded-lg text-danger hover:bg-red-50"><Trash2 className="size-4"/></button></div>)}</div><button type="button" onClick={()=>setSchema((value)=>({...value,evidenceRules:[...value.evidenceRules,{id:crypto.randomUUID(),type:"MIN_PHOTOS",minCount:1}]}))} className="mt-3 min-h-11 rounded-xl border px-4 text-sm font-bold">+ Tambah evidence rule</button></section>
      <div className="sticky bottom-4 mt-6 flex justify-end"><button className="min-h-12 rounded-xl bg-coral-600 px-6 font-extrabold text-white shadow-lg hover:bg-coral-700">Simpan draft</button></div>
    </div></DndContext></form>;
}

function SortableSection({ sortable, section, sectionIndex, canDelete, onTitle, onDelete, onAdd, children }: { sortable: { id: string }; section: ChecklistSchema["sections"][number]; sectionIndex: number; canDelete: boolean; onTitle: (value: string)=>void; onDelete: ()=>void; onAdd: (type: ChecklistFieldType)=>void; children: React.ReactNode }) {
  const state = useSortable({ id: sortable.id, data: { kind: "section", sectionId: section.id } });
  return <section ref={state.setNodeRef} style={{ transform: CSS.Transform.toString(state.transform), transition: state.transition }} className="rounded-2xl border border-coral-200 bg-cream-50 p-4"><header className="mb-4 flex items-center gap-2"><button type="button" aria-label="Geser section" className="grid min-h-11 min-w-11 cursor-grab place-items-center rounded-lg hover:bg-white" {...state.attributes} {...state.listeners}><GripVertical className="size-5"/></button><span className="text-sm font-extrabold text-coral-700">{sectionIndex+1}</span><input aria-label="Judul section" value={section.title} onChange={(event)=>onTitle(event.target.value)} className="min-h-11 min-w-0 flex-1 rounded-lg border bg-white px-3 font-extrabold"/>{canDelete?<button type="button" onClick={onDelete} aria-label="Hapus section" className="grid min-h-11 min-w-11 place-items-center rounded-lg text-danger hover:bg-red-50"><Trash2 className="size-4"/></button>:null}</header><SortableContext items={section.fields.map((field)=>`field:${field.id}`)} strategy={verticalListSortingStrategy}><div className="space-y-3">{children}</div></SortableContext><select aria-label="Tambah field ke section" defaultValue="" onChange={(event)=>{if(event.target.value){onAdd(event.target.value as ChecklistFieldType);event.target.value="";}}} className="mt-3 min-h-11 rounded-xl border bg-white px-3 text-sm font-bold"><option value="">+ Tambah field di section ini</option>{checklistFieldTypes.map((type)=><option key={type} value={type}>{labels[type]}</option>)}</select></section>;
}
