import Link from "next/link";
import { redirect } from "next/navigation";
import { CalendarDays, Columns3, Download, Plus } from "lucide-react";
import { PageHeader, inputClass } from "@/components/forms/master-data";
import { StatusBadge } from "@/components/work-orders/status-badge";
import { WorkOrderForm } from "@/components/work-orders/work-order-form";
import { hasPermission } from "@/modules/memberships/permissions";
import { getWorkOrderFormOptions, listWorkOrders } from "@/modules/work-orders/service";
import { workOrderListSchema } from "@/modules/work-orders/validation";
import { requireTenantContext } from "@/server/auth/tenant";
import { bulkAssignWorkOrdersAction, createWorkOrderAction } from "../work-order-actions";

export default async function WorkOrdersPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const[tenant,raw]=await Promise.all([requireTenantContext(),searchParams]);if(!hasPermission(tenant.role,"work_order:manage"))redirect("/app/dashboard");const parsed=workOrderListSchema.parse({search:raw.search||undefined,status:raw.status||undefined,priority:raw.priority||undefined,sort:raw.sort||undefined,page:raw.page||undefined});const[data,options]=await Promise.all([listWorkOrders({organizationId:tenant.organizationId,...parsed,pageSize:25}),getWorkOrderFormOptions(tenant.organizationId)]);return <main><PageHeader eyebrow="Operations" title="Work orders" description="Rencanakan, tugaskan, dan pantau pekerjaan melalui status workflow yang terkontrol."/>
  <div className="mt-5 flex flex-wrap gap-2"><Link href="/app/work-orders/calendar" className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><CalendarDays className="size-4"/>Calendar</Link><Link href="/app/work-orders/kanban" className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><Columns3 className="size-4"/>Kanban</Link><Link href="/app/work-orders/export" className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold"><Download className="size-4"/>Export CSV</Link></div>
  <details className="mt-5 rounded-2xl border bg-white p-5"><summary className="flex cursor-pointer items-center gap-2 font-extrabold text-coral-700"><Plus className="size-5"/>Create work order</summary><div className="mt-5"><WorkOrderForm action={createWorkOrderAction} options={options}/></div></details>
  <form className="mt-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[2fr_1fr_1fr_1fr_auto]"><input name="search" defaultValue={parsed.search} placeholder="Cari nomor, judul, client, site" className={`${inputClass} mt-0`}/><select name="status" defaultValue={parsed.status??""} className={`${inputClass} mt-0`}><option value="">Semua status</option>{["DRAFT","SCHEDULED","ASSIGNED","IN_PROGRESS","SUBMITTED","UNDER_REVIEW","REVISION_REQUIRED","APPROVED","COMPLETED","CANCELLED"].map((value)=><option key={value}>{value}</option>)}</select><select name="priority" defaultValue={parsed.priority??""} className={`${inputClass} mt-0`}><option value="">Semua priority</option>{["LOW","NORMAL","HIGH","URGENT"].map((value)=><option key={value}>{value}</option>)}</select><select name="sort" defaultValue={parsed.sort} className={`${inputClass} mt-0`}><option value="newest">Terbaru</option><option value="oldest">Terlama</option><option value="schedule_asc">Jadwal terdekat</option><option value="due_asc">Due date terdekat</option><option value="priority">Priority</option></select><button className="min-h-11 rounded-xl bg-ink px-5 font-bold text-white">Filter</button></form>
  <form action={bulkAssignWorkOrdersAction} className="mt-5"><div className="mb-3 flex flex-wrap items-center gap-2 rounded-xl bg-cream-100 p-3"><select required name="membershipId" className="min-h-11 rounded-xl border bg-white px-3 text-sm font-bold"><option value="">Bulk assign ke…</option>{options.members.filter((member)=>["FIELD_WORKER","SUPERVISOR"].includes(member.role)).map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select><button className="min-h-11 rounded-xl bg-coral-600 px-4 text-sm font-bold text-white">Assign selected</button></div><div className="space-y-3">{data.rows.map(({workOrder,clientName,siteName})=><article key={workOrder.id} className="flex items-start gap-3 rounded-2xl border bg-white p-5"><input aria-label={`Pilih ${workOrder.number}`} type="checkbox" name="workOrderIds" value={workOrder.id} className="mt-1 size-5"/><Link href={`/app/work-orders/${workOrder.id}`} className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={workOrder.status}/><span className="text-xs font-extrabold text-coral-700">{workOrder.priority}</span>{workOrder.recurrenceFrequency?<span className="text-xs font-bold text-muted">↻ {workOrder.recurrenceFrequency}</span>:null}</div><h2 className="mt-2 font-extrabold">{workOrder.title}</h2><p className="mt-1 text-sm text-ink-soft">{workOrder.number} · {clientName} · {siteName}</p><p className="mt-2 text-xs font-semibold text-muted">{workOrder.scheduleStart?workOrder.scheduleStart.toLocaleString("id-ID"):"Belum dijadwalkan"}</p></Link></article>)}{!data.rows.length?<div className="rounded-2xl border border-dashed p-8 text-center text-ink-soft">Belum ada work order yang cocok.</div>:null}</div></form><p className="mt-5 text-sm font-semibold text-muted">Menampilkan {data.rows.length} dari {data.total} work order · Halaman {parsed.page}</p></main>}
