import { and, eq } from "drizzle-orm";
import { notFound, redirect } from "next/navigation";
import { FormField, PageHeader, Submit, TextAreaField, inputClass } from "@/components/forms/master-data";
import { getClient } from "@/modules/clients/service";
import { hasPermission } from "@/modules/memberships/permissions";
import { requireTenantContext } from "@/server/auth/tenant";
import { getDatabase } from "@/server/db/client";
import { clientReviewers, memberships, users } from "@/server/db/schema";
import { archiveClientAction, clientReviewerAction, updateClientAction } from "../../master-data-actions";

export default async function ClientDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [tenant,{id}] = await Promise.all([requireTenantContext(),params]); if(!hasPermission(tenant.role,"client:manage")) redirect("/app/dashboard");
  const client = await getClient(tenant.organizationId,id); if(!client) notFound();
  const db=getDatabase();const [availableReviewers,assigned]=await Promise.all([db.select({id:memberships.id,name:users.name,email:users.email}).from(memberships).innerJoin(users,eq(users.id,memberships.userId)).where(and(eq(memberships.organizationId,tenant.organizationId),eq(memberships.role,"CLIENT_REVIEWER"),eq(memberships.status,"ACTIVE"))),db.select({id:memberships.id,name:users.name,email:users.email}).from(clientReviewers).innerJoin(memberships,eq(memberships.id,clientReviewers.membershipId)).innerJoin(users,eq(users.id,memberships.userId)).where(eq(clientReviewers.clientId,client.id))]);
  return <main><PageHeader eyebrow={client.code} title={client.name} description="Perubahan tetap tenant-scoped dan dicatat di audit trail." /><form action={updateClientAction} className="mt-6 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><input type="hidden" name="id" value={client.id}/><FormField label="Client code" name="code" defaultValue={client.code} required/><FormField label="Nama perusahaan" name="name" defaultValue={client.name} required/><FormField label="Contact person" name="contactPerson" defaultValue={client.contactPerson}/><FormField label="Email" name="email" type="email" defaultValue={client.email}/><FormField label="Telepon" name="phone" defaultValue={client.phone}/><label className="text-sm font-bold">Status<select name="status" defaultValue={client.status} className={inputClass}><option>ACTIVE</option><option>INACTIVE</option></select></label><div className="sm:col-span-2"><TextAreaField label="Billing address" name="billingAddress" defaultValue={client.billingAddress}/></div><div className="sm:col-span-2"><TextAreaField label="Catatan" name="notes" defaultValue={client.notes}/></div><div className="sm:col-span-2"><Submit>Simpan perubahan</Submit></div></form><section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-lg font-extrabold">Client reviewers</h2><form action={clientReviewerAction} className="mt-3 flex gap-2"><input type="hidden" name="clientId" value={client.id}/><select name="membershipId" className="min-h-11 flex-1 rounded-xl border px-3" required><option value="">Pilih reviewer</option>{availableReviewers.map((reviewer)=><option key={reviewer.id} value={reviewer.id}>{reviewer.name} · {reviewer.email}</option>)}</select><button name="intent" value="assign" className="rounded-xl bg-coral-600 px-4 font-bold text-white">Assign</button></form><div className="mt-3 space-y-2">{assigned.map((reviewer)=><div key={reviewer.id} className="flex justify-between rounded-xl bg-cream-50 p-3"><span className="text-sm font-semibold">{reviewer.name} · {reviewer.email}</span><form action={clientReviewerAction}><input type="hidden" name="clientId" value={client.id}/><input type="hidden" name="membershipId" value={reviewer.id}/><button name="intent" value="remove" className="text-sm font-bold text-danger">Hapus</button></form></div>)}</div></section><form action={archiveClientAction} className="mt-4"><input type="hidden" name="id" value={client.id}/><Submit danger>Archive client</Submit></form></main>;
}
