import { eq } from "drizzle-orm";
import { redirect } from "next/navigation";
import { FormField, PageHeader, Submit, inputClass } from "@/components/forms/master-data";
import { hasPermission } from "@/modules/memberships/permissions";
import { requireTenantContext } from "@/server/auth/tenant";
import { getDatabase } from "@/server/db/client";
import { organizations, organizationSettings } from "@/server/db/schema";
import { updateOrganizationSettingsAction } from "../../master-data-actions";

export default async function OrganizationSettingsPage(){const tenant=await requireTenantContext();if(!hasPermission(tenant.role,"organization:manage"))redirect("/app/dashboard");const[organization,settings]=await Promise.all([getDatabase().select().from(organizations).where(eq(organizations.id,tenant.organizationId)).limit(1).then(r=>r[0]),getDatabase().select().from(organizationSettings).where(eq(organizationSettings.organizationId,tenant.organizationId)).limit(1).then(r=>r[0])]);return <main><PageHeader eyebrow="Settings" title="Pengaturan organisasi" description="Privasi lokasi, bahasa, zona waktu, dan retensi data berlaku untuk seluruh organization."/><form action={updateOrganizationSettingsAction} className="mt-6 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><FormField label="Nama organisasi" name="name" defaultValue={organization.name} required/><FormField label="Industri" name="industry" defaultValue={organization.industry}/><FormField label="Country code" name="country" defaultValue={organization.country} required/><FormField label="Timezone" name="timezone" defaultValue={organization.timezone} required/><label className="text-sm font-bold">Bahasa<select name="locale" defaultValue={organization.locale} className={inputClass}><option value="id-ID">Bahasa Indonesia</option><option value="en-US">English</option></select></label><FormField label="Retensi data (hari)" name="dataRetentionDays" type="number" defaultValue={settings?.dataRetentionDays??"365"} required/><label className="flex min-h-11 items-center gap-3 rounded-xl border px-4"><input type="checkbox" name="gpsEnabled" defaultChecked={settings?.gpsEnabled}/><span className="text-sm font-bold">Izinkan permintaan GPS dengan consent</span></label><label className="flex min-h-11 items-center gap-3 rounded-xl border px-4"><input type="checkbox" name="clientApprovalEnabled" defaultChecked={settings?.clientApprovalEnabled}/><span className="text-sm font-bold">Aktifkan client approval</span></label><div className="sm:col-span-2"><Submit>Simpan pengaturan</Submit></div></form></main>}
