import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ExternalLink, MapPin, Phone } from "lucide-react";
import { ChecklistExecutor } from "@/components/execution/checklist-executor";
import { PageHeader } from "@/components/forms/master-data";
import { getExecutionDetail } from "@/modules/execution/service";
import { hasPermission } from "@/modules/memberships/permissions";
import { checklistSchema } from "@/modules/templates/validation";
import { requireTenantContext } from "@/server/auth/tenant";

export default async function ExecuteWorkOrderPage({params}:{params:Promise<{id:string}>}){const[tenant,route]=await Promise.all([requireTenantContext(),params]);if(!hasPermission(tenant.role,"work_order:execute"))redirect("/app/dashboard");let detail;try{detail=await getExecutionDetail(tenant.organizationId,tenant.membershipId,route.id);}catch{notFound();}const work=detail.workOrder;const schema=checklistSchema.parse(detail.templateSnapshot);return <main className="mx-auto w-full max-w-3xl"><PageHeader eyebrow={work.number} title={work.title} description={`${detail.clientName} · ${detail.siteName}`}/><section className="mt-5 rounded-2xl border bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs font-extrabold uppercase text-muted">Jadwal</p><p className="mt-1 font-bold">{work.scheduleStart?.toLocaleString("id-ID")??"Belum dijadwalkan"}</p></div><div><p className="text-xs font-extrabold uppercase text-muted">Supervisor</p><p className="mt-1 font-bold">{detail.supervisorName??"Belum ditentukan"}</p></div><div className="sm:col-span-2"><p className="text-xs font-extrabold uppercase text-muted">Instruksi</p><p className="mt-1 whitespace-pre-wrap text-sm">{work.instructions||"Tidak ada instruksi khusus."}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Link target="_blank" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(detail.siteAddress)}`} className="inline-flex min-h-12 items-center gap-2 rounded-xl border px-4 font-bold"><MapPin className="size-5"/>Maps<ExternalLink className="size-4"/></Link>{detail.sitePhone?<Link href={`tel:${detail.sitePhone}`} className="inline-flex min-h-12 items-center gap-2 rounded-xl border px-4 font-bold"><Phone className="size-5"/>{detail.siteContact||"Hubungi site"}</Link>:null}</div></section><div className="mt-5"><ChecklistExecutor workOrder={{id:work.id,number:work.number,title:work.title,status:work.status,actualStartedAt:work.actualStartedAt?.toISOString()??null,instructions:work.instructions}} schema={schema} serverDraft={detail.draft?{id:detail.draft.id,version:detail.draft.version,answers:detail.draft.answers,location:detail.draft.location,updatedAt:detail.draft.updatedAt.toISOString()}:null} serverEvidence={detail.evidence}/></div></main>}
